config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  class LoggedInConstraint
    def self.matches?(request)
      current_user = request.env['warden'].user
      !!current_user
    end
  end

  root 'homepage#index'

  match 'oai', to: "oai_pmh#index", via: [:get, :post], as: :oai_provider

  # https://github.com/plataformatec/devise/wiki/how-to:-change-the-default-sign_in-and-sign_out-routes
  # We aren't using :registration cause we don't want to allow self-registration,
  # We aren't using session cause we define em ourselves manually.
  devise_for :users, skip: [:session, :registration]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Dynamic robots.txt
  # this will fall through to ./views/application/robots.txt.erb, no need for an action method
  get 'robots.txt', to: "application#robots.txt", format: "text"

  # On-demand derivatives
  constraints(derivative_type: Regexp.union(OnDemandDerivative.derivative_type_definitions.keys.collect(&:to_s))) do
    get "works/:id/:derivative_type", to: "on_demand_derivatives#on_demand_status", as: :on_demand_derivative_status
  end

  # public-facing routes
  resources :works, only: [:show]

  # JSON info for scihist_viewer image viewer
  get '/works/:id/viewer_images_info' => 'works#viewer_images_info',
    defaults: {format: "json"},
    format: false,
    as: :viewer_images_info

  # Make the viewer  URL lead to ordinary show page, so JS can pick it up and launch viewer.
  get '/works/:id/viewer/:viewer_member_id(.:format)' => 'works#show', as: :viewer


  get '/collections', to: "collections_list#index", as: :collections

  # Our collections show controller provides a Blacklight search, so needs
  # some additional routes for various search behaviors too.
  get "/collections/:collection_id", to: "collection_show#index", as: :collection
  get "collections/:collection_id/range_limit" => "collection_show#range_limit"
  get "collections/:collection_id/range_limit_panel" => "collection_show#range_limit_panel"
  get "collections/:collection_id/facet" => "collection_show#facet"

  get "focus/:slug", to: "featured_topic#index", as: :featured_topic
  get "focus/:slug/range_limit" => "featured_topic#range_limit"
  get "focus/:slug/range_limit_panel" => "featured_topic#range_limit_panel"
  get "focus/:slug/facet" => "featured_topic#facet"


  # download_path(asset)
  # download_url(asset)
  get "downloads/:asset_id", to: "downloads#original", as: :download
  # download_derivative_path(asset, "thumb_small")
  # download_derivative_url(asset, "thumb_small")
  get "downloads/:asset_id/:derivative_key", to: "downloads#derivative", as: :download_derivative


  ##
  # Blacklight-generated routes, that were then modified a bit by us to take
  # out stuff we're not using.
  #

      # Route RSS and atom search results to a 404
      # until we decide to implement them.
      # Practically speaking, this only affects bots).
      get 'catalog.rss',  to: proc { [404, {}, ['']] }
      get 'catalog.atom', to: proc { [404, {}, ['']] }
      get 'catalog.json', to: proc { [404, {}, ['']] }

      # TODO: Can we get away without actuallymounting Blacklight, just using the CatalogController?
      # mount Blacklight::Engine => '/'
      concern :searchable, Blacklight::Routes::Searchable.new
      resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
        concerns :searchable
        concerns :range_searchable # for blacklight_range_limit
      end

      # We aren't using default Blacklight action for 'show' item, instead using our
      # own ActiveRecord-model based show, so don't need to route SolrDocumentController...
      # we think, at least for now.
      #
      # concern :exportable, Blacklight::Routes::Exportable.new
      # resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
      #   concerns :exportable
      # end

      # We aren't using bookmarks, and don't have to route them
      # --jrochkind
      # resources :bookmarks do
      #   concerns :exportable

      #   collection do
      #     delete 'clear'
      #   end
      # end
  ##
  # End Blacklight-generated routes
  ##

  # Routes will even only _show up_ to logged in users, this applies
  # to internal rack apps we're mounting here too, like shrine upload endpoints,
  # is one reason to use a constraint.
  namespace :admin do
    root to: "works#index"

    resources :users, except: [:destroy, :show] do
      member do
        post "send_password_reset"
      end
    end

    # Admin page for work management, we'll handle public view elsewhere
    resources :works do
      member do
        get "reorder_members", to: "works#reorder_members_form"
        put "reorder_members"
        put "demote_to_asset"
        put "publish"
        put "unpublish"
        put "submit_ohms_xml"
        put "create_combined_audio_derivatives"
      end
      collection do
        get 'batch_update', to: "works#batch_update_form"
        post 'batch_update'
      end
    end

    get "/works/:parent_id/ingest", to: "assets#display_attach_form", as: "asset_ingest"
    post "/works/:parent_id/ingest", to: "assets#attach_files"


    resources :collections, except: [:show]

    # Note "assets" is Rails reserved word for routing, oops. So we use
    # asset_files.
    resources :assets, path: "asset_files", except: [:new, :create] do
      member do
        put "convert_to_child_work"
      end
    end

    post "/asset_files/:asset_id/check_fixity", to: "assets#check_fixity", as: "check_fixity"
    get "/fixity_report", to: "assets#fixity_report", as: "fixity_report"

    get "/batch_create", to: "batch_create#new", as: "batch_create" # step 1
    post "/batch_create", to: "batch_create#add_files" # step 2
    post "/batch_create/finish", to: "batch_create#create" # step 3, create and redirect

    resources :digitization_queue_items, except: [:index, :create, :new, :destroy] do
      collection do
        get "collecting_areas"

        # index, new and create need a /$collecting_area on them.
        constraints(proc {|params, req|
            Admin::DigitizationQueueItem::COLLECTING_AREAS.include?(params[:collecting_area])
        }) do
          get ":collecting_area", to: "digitization_queue_items#index", as: ""
          post ":collecting_area", to: "digitization_queue_items#create", as: nil
          get ":collecting_area/new", to: "digitization_queue_items#new", as: "new"
        end
      end
      member do
        post :add_comment
      end
    end

    resources :r_and_r_items do
      member do
        post :add_comment
      end
    end

    delete  "digitization_queue_items/:id/delete_comment/:comment_id",
      to: "digitization_queue_items#delete_comment",
      as: "delete_digitization_queue_item_comment"

    delete  "r_and_r_items/:id/delete_comment/:comment_id",
      to: "r_and_r_items#delete_comment",
      as: "delete_r_and_r_comment"

    resources :cart_items, param: :work_friendlier_id, only: [:index, :update, :destroy] do
      collection do
        delete 'clear'
      end
    end


    # These 'sub-apps' are for admin-use only, but since they are sub-apps
    # aren't protected by the AdminController. We have Rails routing only
    # provide the routes if there is a logged-in user.
    constraints LoggedInConstraint do
      mount Resque::Server, at: '/queues'

      mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", as: :direct_app_upload

      if Shrine.storages[:cache].kind_of?(Shrine::Storage::S3)
        mount Shrine.uppy_s3_multipart(:cache) => "/s3"
      end
    end
  end

  # We can't put browse-everything in the routing namespace, cause it breaks
  # browse-everything, alas. We'll still make it route as if it were, and
  # add a routing constraint to protect to just logged in users.
  constraints LoggedInConstraint do
    mount BrowseEverything::Engine => '/admin/browse'

    # Don't know if we really need qa to be limited to logged-in users, but
    # that's the only place we use it, so let's limit to avoid anyone DOSing
    # us with it or whatever.
    #
    # And we mount it as '/authorities' rather than '/qa' that the installer
    # wanted, to match sufia/hyrax and be less weird.
    mount Qa::Engine => '/authorities'
  end


  # Tell Rails polymorphic routing to assume :admin namespace for works,
  # so we can just do `url_for @work` and get /admin/works.
  #
  # May not actually be a good idea? What will we do when we add non-admin show?
  resolve("Work") do |work, options|
    [:admin, work, options]
  end
  resolve("Asset") do |asset, options|
    [:admin, asset, options]
  end
  resolve("Collection") do |collection, options|
    [:admin, collection, options]
  end

  #Static pages
  %w(about contact faq policy).each do |page_label|
    get page_label, controller: 'static', action: page_label, as: page_label
  end

end

app/controllers/admin/digitization_queue_items_controller.rb
class Admin::DigitizationQueueItemsController < AdminController
  before_action :set_admin_digitization_queue_item, only: [:show, :edit, :update, :destroy, :add_comment, :delete_comment]

  # GET /admin/digitization_queue_items
  # GET /admin/digitization_queue_items.json
  def index
    @admin_digitization_queue_items = filtered_index_items
  end

  # GET /admin/digitization_queue_items/1
  # GET /admin/digitization_queue_items/1.json
  def show
  end

  # GET /admin/digitization_queue_items/new
  def new
    @admin_digitization_queue_item = Admin::DigitizationQueueItem.new(collecting_area: params[:collecting_area])
    if params[:r_and_r_item]
      r_and_r_item = Admin::RAndRItem.find(params[:r_and_r_item])
      @admin_digitization_queue_item.r_and_r_item_id = r_and_r_item.id
      r_and_r_item.fill_out_digitization_queue_item(@admin_digitization_queue_item)
    end
  end

  # GET /admin/digitization_queue_items/1/edit
  def edit
  end

  # POST /admin/digitization_queue_items
  # POST /admin/digitization_queue_items.json
  def create
    @admin_digitization_queue_item = Admin::DigitizationQueueItem.new(admin_digitization_queue_item_params)

    respond_to do |format|
      if @admin_digitization_queue_item.save
        format.html { redirect_to admin_digitization_queue_items_url(@admin_digitization_queue_item.collecting_area), notice: 'Digitization queue item was successfully created.' }
        format.json { render :show, status: :created, location: admin_digitization_queue_items_url(@admin_digitization_queue_item.collecting_area) }
      else
        format.html { render :new }
        format.json { render json: @admin_digitization_queue_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/digitization_queue_items/1
  # PATCH/PUT /admin/digitization_queue_items/1.json
  def update
    respond_to do |format|
      if update_with_action_comments(@admin_digitization_queue_item, admin_digitization_queue_item_params)
        notice = 'Digitization queue item was successfully updated.'
        format.html { redirect_to @admin_digitization_queue_item, notice: notice }
        format.json { render json: { notice: notice } }
      else
        format.html { render :edit }
        format.json { render json: @admin_digitization_queue_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /admin/digitization_queue_items/collecting_areas
  # Just lists our top-level collecting areas
  def collecting_areas
    @open_counts = Admin::DigitizationQueueItem.open_status.group(:collecting_area).count
  end

  # DELETE /admin/digitization_queue_items/1
  # DELETE /admin/digitization_queue_items/1.json
  # def destroy
  #   @admin_digitization_queue_item.destroy
  #   respond_to do |format|
  #     format.html { redirect_to admin_digitization_queue_items_url(collecting_area), notice: 'Digitization queue item was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  def collecting_area
    @admin_digitization_queue_item.try(:collecting_area) || params.fetch(:collecting_area)
  end
  helper_method :collecting_area

  # POST /admin/digitization_queue_item/1/add_comment
  def add_comment
    if params["comment"].present?
      Admin::QueueItemComment.create!(
        user: current_user,
        digitization_queue_item: @admin_digitization_queue_item,
        text: params["comment"]
      )
    end

    redirect_to @admin_digitization_queue_item
  end

  # admin_delete_comment
  # DELETE
  # /admin/digitization_queue_items/:id/delete_comment/:comment_id(.:format)
  # admin/digitization_queue_items#delete_comment
  def delete_comment
    comment = Admin::QueueItemComment.find_by_id(params['comment_id'])
    raise ArgumentError.new( 'Could not find this comment.') if comment.nil?
    if can?(:destroy, comment)
      comment.delete
      notice = 'Comment deleted.'
    else
      notice = 'You may not delete this comment.'
    end
    redirect_to @admin_digitization_queue_item,
      notice: notice
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_digitization_queue_item
      @admin_digitization_queue_item = Admin::DigitizationQueueItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_digitization_queue_item_params
      params.require(:admin_digitization_queue_item).permit(
        :title, :status, :accession_number, :museum_object_id, :bib_number, :location,
        :box, :folder, :dimensions, :materials, :copyright_status,
        :scope, :instructions, :additional_notes, :collecting_area,
        :r_and_r_item_id
      )
    end

    def filtered_index_items
      scope = Admin::DigitizationQueueItem.where(collecting_area: collecting_area).order(status_changed_at: :asc)

      if (q = params.dig(:query, :q)).present?
        scope = scope.where("title like ? OR bib_number = ? or accession_number = ? OR museum_object_id = ?", "%#{q}%", q, q, q)
      end

      status = params.dig(:query, :status)
      if status == "ANY"
        # no-op, no filter
      elsif status.blank? # default, "open"
        scope = scope.open_status
      else
        scope = scope.where(status: status)
      end


      scope.page(params[:page]).per(100)
    end

    # hacky helper to give us select menu options for status filter
    #
    # The 'nil' option is actually 'closed', that we want to be default
    def status_filter_options
      helpers.options_for_select([["Any", "ANY"]], params.dig(:query, :status)) +
      helpers.grouped_options_for_select(
        { "open/closed" => [["Open", ""], ["Closed", "closed"]],
          "status" =>  Admin::DigitizationQueueItem::STATUSES.
            find_all {|s| s != "closed" }.
            collect {|s| [s.humanize, s]}
        },
        params.dig(:query, :status) || ""
      )

      # helpers.options_for_select(
      #   Admin::DigitizationQueueItem::STATUSES.
      #     find_all {|s| s != "closed" }.
      #     collect {|s| [s.humanize, s]},
      #   params.dig(:query, :status)
      # )
    end
    helper_method :status_filter_options

    # one way to make sure after we save a queue item, it gets a comment
    # recorded for status changes,in the same transaction, without using
    # AR callbacks (and so we have access to current_user)
    #
    # with_action_comments do
    #    save_a_queue_item
    # end
    def update_with_action_comments(queue_item, params)
      result = nil
      queue_item.class.transaction do
        result = queue_item.update(params)
        if result && queue_item.saved_change_to_status?
          queue_item.queue_item_comments.create!(system_action: true, user: current_user, text: "marked: #{queue_item.status.humanize.downcase}")
        end
      end
      result
    end
end

app/helpers/digitization_queue_items_helper.rb
module DigitizationQueueItemsHelper
  # just a hacky helper to show a dt/dd for a given Admin::DigitizationQueueItem field,
  # if present, we could be using presenters, or something else. This gets us started
  # with a basic show view.
  def queue_item_show_field(item, field, humanize_value: false, paragraphs: false, override_label: nil)
    value = item.send(field)
    if value.present?
      if humanize_value
        value = value.humanize
      end
      if paragraphs
        value = simple_format(value)
      end

      content_tag("dt", (override_label || field.to_s.titleize)) +
        content_tag("dd", value)
    end
  end
end

app/views/admin/digitization_queue_items/_form.html.erb
<%= simple_form_for(@admin_digitization_queue_item, :html=> { novalidate: true }) do |f| %>


  <%# This hidden field tag is only used when we create a new digitization queue item *based* on an R&R item.
  The tag keeps a reference to the old R&R item. %>
  <% if !@admin_digitization_queue_item.persisted? && @admin_digitization_queue_item.r_and_r_item_id %>
    <%= hidden_field_tag "admin_digitization_queue_item[r_and_r_item_id]", @admin_digitization_queue_item.r_and_r_item_id  %>
  <% end %>

  <% if @admin_digitization_queue_item.errors.any? %>

    <div class="kithe-form-errors-top alert alert-danger mb-4" role="alert">
      <h2 class="h4" class="alert-heading"><%= pluralize(@admin_digitization_queue_item.errors.count, "error") %> prohibited this work from being saved</h2>
      <ol class="mb-0">
        <% @admin_digitization_queue_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ol>
    </div>
  <% end %>


  <div class="form-inputs">
    <% if ["new", "create"].include?(params[:action].to_s) %>
      <%= f.hidden_field :collecting_area, value: collecting_area %>
    <% end %>

    <%= f.input :title, hint: "or Object Name/Description" %>

    <div class="row">
      <div class="col-6">
        <%= f.input :status,
          label: "Digitization Queue Status",
          collection: Admin::DigitizationQueueItem::STATUSES.collect {|s| [s.humanize, s]},
          include_blank: false %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :accession_number, required: f.object.field_is_required_for_collecting_area?(:accession_number) %>
      </div>
      <div class="col">
        <%= f.input :museum_object_id, required: f.object.field_is_required_for_collecting_area?(:museum_object_id) %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :bib_number,
              hint: (f.object.field_is_required_for_collecting_area?(:bib_number) ? "for #{self.collecting_area.humanize.singularize} item" : "if applicable" ),
              required: f.object.field_is_required_for_collecting_area?(:bib_number) %>
      </div>
      <div class="col">
        <%= f.input :location,
              hint: "Call number, Home Location, etc.",
              required: f.object.field_is_required_for_collecting_area?(:location) %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :box %>
      </div>
      <div class="col">
        <%= f.input :folder %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :dimensions %>
      </div>
      <div class="col">
        <%= f.input :materials %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :scope, hint: "Pages, Components, etc." %>
      </div>
      <div class="col">
        <%= f.input :instructions, hint: "Staging notes, handling instructions, etc." %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :copyright_status, as: :text %>
      </div>
      <div class="col">
        <%= f.input :additional_notes, label: "Additional notes <small>(shows up on list view)</small>".html_safe %>
      </div>
    </div>
  </div>

  <div class="form-actions mb-3">
    <%= link_to "Cancel", admin_digitization_queue_items_path(collecting_area), class: "btn btn-outline-primary" %>
    <%= f.button :submit %>
  </div>

</div>
<% end %>

app/views/admin/digitization_queue_items/collecting_areas.erb
<h1>Digitization Queue Collecting Areas</h1>

<ul class="list-unstyled">
  <% Admin::DigitizationQueueItem::COLLECTING_AREAS.each do |area| %>
    <li>
      <h2>
        <%= link_to area.titleize, admin_digitization_queue_items_path(area) %>
        <small>(<%= @open_counts[area].to_i %> open)</small>
      </h2>
    </li>
  <% end %>
</ul>

app/views/admin/digitization_queue_items/edit.html.erb
<h1>Editing Digitization Queue Item</h1>

<%= render 'form', admin_digitization_queue_item: @admin_digitization_queue_item %>

app/views/admin/digitization_queue_items/index.html.erb
<h1>Digitization Queue: <%= collecting_area.humanize %></h1>

<p>
<%= link_to 'New Queue Item', new_admin_digitization_queue_items_path(collecting_area), class: "btn btn-primary" %>
</p>

<div class="my-2">
  <%= simple_form_for(:query, url: admin_digitization_queue_item_path(collecting_area), method: :get) do |f| %>
    <div class="row form-group">
      <div class="col-sm-10">
        <small class="text-muted">Title, or ID (bib, accession, or object)</small>
      </div>
      <div class="input-group col-sm-10">
        <div class="input-group-prepend">
          <%= f.label :q, "Search", class: "input-group-text" %>
        </div>
        <%= f.search_field :q, class: "form-control", value: params.dig(:query, :q) %>
        <div class="input-group-append">
          <%= f.button :submit, value: "Go", class: "btn btn-primary" %>
        </div>
      </div>
    </div>

    <div class="row form-group">
      <div class="input-group col-sm-10">
        <div class="input-group-prepend">
          <%= f.label :status, "Status", class: "input-group-text" %>
        </div>

        <%= f.select :status,
            status_filter_options,
            { selected: "closed"},
            {
              class: "custom-select",
              onchange: "this.form.submit()"
            }
        %>
      </div>
    </div>
  <% end %>
</div>

<% if @admin_digitization_queue_items.total_count > 0 %>
  <p>
    <%= @admin_digitization_queue_items.offset_value + 1 %> - <%= @admin_digitization_queue_items.offset_value + @admin_digitization_queue_items.count %> of <%= @admin_digitization_queue_items.total_count %>
  </p>
<% end %>


<div class="table-responsive">
  <table class="table" style="table-layout: fixed; font-size: 90%; min-width: 55rem; word-break: break-word;">
    <thead>
      <tr>
        <th style="width: 4.5rem;"></th>
        <th>title</th>
        <th style="width: 6rem;">bib #</th>
        <th style="width: 6rem;">acc. #</th>
        <th style="width: 8rem;">object id</th>
        <th style="width: 11rem;">status</th>
        <th style="width: 8rem;">status changed</th>
      </tr>
    </thead>

    <tbody>
      <% @admin_digitization_queue_items.each do |admin_digitization_queue_item| %>
        <tr>
          <td>
            <%= link_to 'Edit', edit_admin_digitization_queue_item_path(admin_digitization_queue_item), class: "btn btn-sm btn-outline-primary" %>
          </td>
          <td>
            <%= link_to admin_digitization_queue_item.title, admin_digitization_queue_item_path(admin_digitization_queue_item) %>
            <% if admin_digitization_queue_item.additional_notes.present? %>
              <p class="mb-0">
                <%= admin_digitization_queue_item.additional_notes %>
              </p>
            <% end %>
            <% if admin_digitization_queue_item.location.present? %>
              <p class="mb-0">
                <b>Location:</b> <%= admin_digitization_queue_item.location %>
              </p>
            <% end %>
          </td>
          <td><%= admin_digitization_queue_item.bib_number %></td>
          <td><%= admin_digitization_queue_item.accession_number %></td>
          <td><%= admin_digitization_queue_item.museum_object_id %></td>
          <td>
             <%= DigitizationQueueItemStatusForm.new(admin_digitization_queue_item).display %>
          </td>
          <td><%= l(admin_digitization_queue_item.status_changed_at.to_date, format: :admin) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @admin_digitization_queue_items, theme: 'twitter-bootstrap-4' %>

app/views/admin/digitization_queue_items/new.html.erb
<h1>New Digitization Queue Item</h1>
<h1 class="h4">Collecting Area: <%= collecting_area.humanize %></h1>

<%= render 'form', admin_digitization_queue_item: @admin_digitization_queue_item %>

app/views/admin/digitization_queue_items/show.html.erb
<div class="mb-2">
  <div>Digitization Queue: <%= link_to @admin_digitization_queue_item.collecting_area.humanize, admin_digitization_queue_items_url(@admin_digitization_queue_item.collecting_area) %></div>
  <h1><%= @admin_digitization_queue_item.title %></h1>
</div>

<div class="row">
  <div class="col-lg-5 pr-4 mb-4">
    <%= DigitizationQueueItemStatusForm.new(@admin_digitization_queue_item).display %>
  </div>
</div>

<div class="row">
  <div class="col-md-7 order-md-2">
    <p>
    <%= link_to 'Edit Queue item', edit_admin_digitization_queue_item_path(@admin_digitization_queue_item), class: "btn btn-primary" %>
    </p>

    <% if @admin_digitization_queue_item.bib_number.present? %>
      <p>
        <%= link_to "OPAC link (#{@admin_digitization_queue_item.bib_number})", ScihistDigicoll::Util.opac_url(@admin_digitization_queue_item.bib_number), target: "_blank" %>
      </p>
    <% end %>

    <dl>
      <%= queue_item_show_field(@admin_digitization_queue_item, :title) %>

      <dt>Collecting area</dt>
      <dd><%= link_to @admin_digitization_queue_item.collecting_area.humanize, admin_digitization_queue_items_url(@admin_digitization_queue_item.collecting_area) %></dd>

      <dt>Created at</dt>
      <dd>
        <%= l @admin_digitization_queue_item.created_at, format: :admin %>
      </dd>


      <dt>Status</dt>
      <dd>
        <%= @admin_digitization_queue_item.status.humanize %> (<%= l @admin_digitization_queue_item.status_changed_at, format: :admin %>)
      </dd>


      <%= queue_item_show_field(@admin_digitization_queue_item, :bib_number) %>
      <%= queue_item_show_field(@admin_digitization_queue_item, :location) %>
      <%= queue_item_show_field(@admin_digitization_queue_item, :accession_number) %>
      <%= queue_item_show_field(@admin_digitization_queue_item, :museum_object_id, override_label: "Object ID (Past Perfect)") %>
      <%= queue_item_show_field(@admin_digitization_queue_item, :box) %>
      <%= queue_item_show_field(@admin_digitization_queue_item, :folder) %>

      <%= queue_item_show_field(@admin_digitization_queue_item, :dimensions) %>
      <%= queue_item_show_field(@admin_digitization_queue_item, :materials) %>


      <%= queue_item_show_field(@admin_digitization_queue_item, :scope, paragraphs: true) %>
      <%= queue_item_show_field(@admin_digitization_queue_item, :instructions, paragraphs: true) %>
      <%= queue_item_show_field(@admin_digitization_queue_item, :additional_notes, paragraphs: true) %>
      <%= queue_item_show_field(@admin_digitization_queue_item, :copyright_status, paragraphs: true) %>

    </dl>
  </div>

  <div class="col-md-5 order-md-1 pr-4">

    <div class="card mb-3">
      <div class="card-header" id="attachedHeading">
        <h2 class="h5 mb-0">
          <a href="#" data-toggle="collapse" data-target="#attachedWorks" aria-expanded="false" aria-controls="attachedWorks">
            <%= @admin_digitization_queue_item.works.count %> Attached Works
          </a>
        </h5>
      </div>

      <div id="attachedWorks" class="collapse" aria-labelledby="attachedHeading">
        <ul class="list-unstyled card-body">
          <% @admin_digitization_queue_item.works.order(updated_at: :desc).each do |work| %>
            <li><%= link_to work.title, admin_work_path(work) %> <%= publication_badge(work) %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <p>
      <%= link_to "Create new attached work", new_admin_work_path(digitization_queue_item: @admin_digitization_queue_item.id), class: "btn btn-primary mb-1" %>
      <%= link_to "Batch create attached works", admin_batch_create_path(digitization_queue_item: @admin_digitization_queue_item.id), class: "btn btn-outline-primary" %>
    </p>

    <h2>Comments</h2>

    <%= form_tag add_comment_admin_digitization_queue_item_path do %>
      <div class="mb-4 text-right">
        <h3 class="h5"><label for="addComment">Add Comment</label></h3>
        <textarea class="form-control" name="comment" id="addComment" rows="3"></textarea>
        <button class="btn btn-primary mt-1">Submit comment</button>
      </div>
    <% end %>

    <% @admin_digitization_queue_item.queue_item_comments.includes(:user).order(created_at: :desc).each do |comment| %>
      <div>
        <div class="card queue-comment mb-3 d-inline-flex <% if comment.system_action? %>text-white bg-info<% end %>">
          <div class="card-header">
            <% if comment.user %>
              <%= comment.user&.name || comment.user&.email %>,
            <% end %>
            <%= time_ago_in_words comment.created_at %> ago
          </div>
          <div class="card-body pb-0">
            <%= simple_format(comment.text) %>
            <% if can?(:destroy, comment) %>
              <div class="text-right">
                <%= link_to "Delete",
                  admin_delete_digitization_queue_item_comment_path(id: @admin_digitization_queue_item.id, comment_id: comment.id),
                  class: "btn btn-primary mb-1",
                  method: 'delete',
                  data: { confirm: "Delete your comment?" }
                %>
              </div>
            <%end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>