config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  class LoggedInConstraint
    def self.matches?(request)
      current_user = request.env['warden'].user
      !!current_user
    end
  end

  root 'homepage#index'

  match 'oai', to: "oai_pmh#index", via: [:get, :post], as: :oai_provider

  # https://github.com/plataformatec/devise/wiki/how-to:-change-the-default-sign_in-and-sign_out-routes
  # We aren't using :registration cause we don't want to allow self-registration,
  # We aren't using session cause we define em ourselves manually.
  devise_for :users, skip: [:session, :registration]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Dynamic robots.txt
  # this will fall through to ./views/application/robots.txt.erb, no need for an action method
  get 'robots.txt', to: "application#robots.txt", format: "text"

  # On-demand derivatives
  constraints(derivative_type: Regexp.union(OnDemandDerivative.derivative_type_definitions.keys.collect(&:to_s))) do
    get "works/:id/:derivative_type", to: "on_demand_derivatives#on_demand_status", as: :on_demand_derivative_status
  end

  # public-facing routes
  resources :works, only: [:show]

  # JSON info for scihist_viewer image viewer
  get '/works/:id/viewer_images_info' => 'works#viewer_images_info',
    defaults: {format: "json"},
    format: false,
    as: :viewer_images_info

  # Make the viewer  URL lead to ordinary show page, so JS can pick it up and launch viewer.
  get '/works/:id/viewer/:viewer_member_id(.:format)' => 'works#show', as: :viewer


  get '/collections', to: "collections_list#index", as: :collections

  # Our collections show controller provides a Blacklight search, so needs
  # some additional routes for various search behaviors too.
  get "/collections/:collection_id", to: "collection_show#index", as: :collection
  get "collections/:collection_id/range_limit" => "collection_show#range_limit"
  get "collections/:collection_id/range_limit_panel" => "collection_show#range_limit_panel"
  get "collections/:collection_id/facet" => "collection_show#facet"

  get "focus/:slug", to: "featured_topic#index", as: :featured_topic
  get "focus/:slug/range_limit" => "featured_topic#range_limit"
  get "focus/:slug/range_limit_panel" => "featured_topic#range_limit_panel"
  get "focus/:slug/facet" => "featured_topic#facet"


  # download_path(asset)
  # download_url(asset)
  get "downloads/:asset_id", to: "downloads#original", as: :download
  # download_derivative_path(asset, "thumb_small")
  # download_derivative_url(asset, "thumb_small")
  get "downloads/:asset_id/:derivative_key", to: "downloads#derivative", as: :download_derivative


  ##
  # Blacklight-generated routes, that were then modified a bit by us to take
  # out stuff we're not using.
  #

      # Route RSS and atom search results to a 404
      # until we decide to implement them.
      # Practically speaking, this only affects bots).
      get 'catalog.rss',  to: proc { [404, {}, ['']] }
      get 'catalog.atom', to: proc { [404, {}, ['']] }
      get 'catalog.json', to: proc { [404, {}, ['']] }

      # TODO: Can we get away without actuallymounting Blacklight, just using the CatalogController?
      # mount Blacklight::Engine => '/'
      concern :searchable, Blacklight::Routes::Searchable.new
      resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
        concerns :searchable
        concerns :range_searchable # for blacklight_range_limit
      end

      # We aren't using default Blacklight action for 'show' item, instead using our
      # own ActiveRecord-model based show, so don't need to route SolrDocumentController...
      # we think, at least for now.
      #
      # concern :exportable, Blacklight::Routes::Exportable.new
      # resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
      #   concerns :exportable
      # end

      # We aren't using bookmarks, and don't have to route them
      # --jrochkind
      # resources :bookmarks do
      #   concerns :exportable

      #   collection do
      #     delete 'clear'
      #   end
      # end
  ##
  # End Blacklight-generated routes
  ##

  # Routes will even only _show up_ to logged in users, this applies
  # to internal rack apps we're mounting here too, like shrine upload endpoints,
  # is one reason to use a constraint.
  namespace :admin do
    root to: "works#index"

    resources :users, except: [:destroy, :show] do
      member do
        post "send_password_reset"
      end
    end

    # Admin page for work management, we'll handle public view elsewhere
    resources :works do
      member do
        get "reorder_members", to: "works#reorder_members_form"
        put "reorder_members"
        put "demote_to_asset"
        put "publish"
        put "unpublish"
        put "submit_ohms_xml"
        put "create_combined_audio_derivatives"
      end
      collection do
        get 'batch_update', to: "works#batch_update_form"
        post 'batch_update'
      end
    end

    get "/works/:parent_id/ingest", to: "assets#display_attach_form", as: "asset_ingest"
    post "/works/:parent_id/ingest", to: "assets#attach_files"


    resources :collections, except: [:show]

    # Note "assets" is Rails reserved word for routing, oops. So we use
    # asset_files.
    resources :assets, path: "asset_files", except: [:new, :create] do
      member do
        put "convert_to_child_work"
      end
    end

    post "/asset_files/:asset_id/check_fixity", to: "assets#check_fixity", as: "check_fixity"
    get "/fixity_report", to: "assets#fixity_report", as: "fixity_report"

    get "/batch_create", to: "batch_create#new", as: "batch_create" # step 1
    post "/batch_create", to: "batch_create#add_files" # step 2
    post "/batch_create/finish", to: "batch_create#create" # step 3, create and redirect

    resources :digitization_queue_items, except: [:index, :create, :new, :destroy] do
      collection do
        get "collecting_areas"

        # index, new and create need a /$collecting_area on them.
        constraints(proc {|params, req|
            Admin::DigitizationQueueItem::COLLECTING_AREAS.include?(params[:collecting_area])
        }) do
          get ":collecting_area", to: "digitization_queue_items#index", as: ""
          post ":collecting_area", to: "digitization_queue_items#create", as: nil
          get ":collecting_area/new", to: "digitization_queue_items#new", as: "new"
        end
      end
      member do
        post :add_comment
      end
    end

    resources :r_and_r_items do
      member do
        post :add_comment
      end
    end

    delete  "digitization_queue_items/:id/delete_comment/:comment_id",
      to: "digitization_queue_items#delete_comment",
      as: "delete_digitization_queue_item_comment"

    delete  "r_and_r_items/:id/delete_comment/:comment_id",
      to: "r_and_r_items#delete_comment",
      as: "delete_r_and_r_comment"

    resources :cart_items, param: :work_friendlier_id, only: [:index, :update, :destroy] do
      collection do
        delete 'clear'
      end
    end


    # These 'sub-apps' are for admin-use only, but since they are sub-apps
    # aren't protected by the AdminController. We have Rails routing only
    # provide the routes if there is a logged-in user.
    constraints LoggedInConstraint do
      mount Resque::Server, at: '/queues'

      mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", as: :direct_app_upload

      if Shrine.storages[:cache].kind_of?(Shrine::Storage::S3)
        mount Shrine.uppy_s3_multipart(:cache) => "/s3"
      end
    end
  end

  # We can't put browse-everything in the routing namespace, cause it breaks
  # browse-everything, alas. We'll still make it route as if it were, and
  # add a routing constraint to protect to just logged in users.
  constraints LoggedInConstraint do
    mount BrowseEverything::Engine => '/admin/browse'

    # Don't know if we really need qa to be limited to logged-in users, but
    # that's the only place we use it, so let's limit to avoid anyone DOSing
    # us with it or whatever.
    #
    # And we mount it as '/authorities' rather than '/qa' that the installer
    # wanted, to match sufia/hyrax and be less weird.
    mount Qa::Engine => '/authorities'
  end


  # Tell Rails polymorphic routing to assume :admin namespace for works,
  # so we can just do `url_for @work` and get /admin/works.
  #
  # May not actually be a good idea? What will we do when we add non-admin show?
  resolve("Work") do |work, options|
    [:admin, work, options]
  end
  resolve("Asset") do |asset, options|
    [:admin, asset, options]
  end
  resolve("Collection") do |collection, options|
    [:admin, collection, options]
  end

  #Static pages
  %w(about contact faq policy).each do |page_label|
    get page_label, controller: 'static', action: page_label, as: page_label
  end

end

app/models/work/additional_credit.rb
class Work
  class AdditionalCredit
    include AttrJson::Model

    ROLES = ['photographed_by']
    NAMES = [
      'Douglas Lockard',
      'Gregory Tobias',
      'Mark Backrath',
      'Penn School of Medicine',
      'Will Brown'
    ]

    # allow_blank keeps us from having double validation error messages for
    # presence and inclusion.
    validates :role, presence: true, inclusion:
      { in: ROLES,
        allow_blank: true,
        message: "%{value} is not a valid credit role" }
    validates :name, presence: true, inclusion:
      { in: NAMES,
        allow_blank: true,
        message: "%{value} is not a valid credit name" }

    attr_json :role, :string
    attr_json :name, :string

    def display_as
      "#{role.humanize} #{name}"
    end
  end
end

app/models/work/controlled_lists.rb
# Constants for various controlled lists for Work attributes.
#
# _Removing_ values from here may require data migration in your existing db.
#
# ## Display lables via i18n
# These are the values actually stored in the DB. Display-translated values can be
# provided via a poorly documented built-in feature of Rails i18n.
#
# If you put an I18n value in your locale file (eg config/locales/en.yml) at:
#     activerecord:
#       attributes:
#         work/format:
#           image: "Really great image"
#
# Then you can look it up with Work.human_attribute_name("format.image"). It even
# does some superclass lookup for you if you have an inheritance hieararchy.
#
# ## Some lists elsewhere
# Controlled values for specific sub-model classes (like Creator) can be found
# within them, not here. This is only for primitive attributes on Work. (But should
# we move sub-model lists here too?)
class Work
  class ControlledLists
    # from https://github.com/sciencehistory/chf-sufia/blob/master/config/authorities/resource_types.yml
    # Note these had corresponding RDF value URIs listed originally, although they weren't used
    # by our sufia app either.
    FORMAT = %w{image mixed_material moving_image physical_object sound text}.freeze

    GENRE = [
      'Advertisements',
      'Artifacts',
      'Business correspondence',
      'Catalogs',
      'Charts, diagrams, etc',
      'Chemistry sets',
      'Clothing & dress',
      'Documents',
      'Drawings',
      'Encyclopedias and dictionaries',
      'Electronics',
      'Engravings',
      'Ephemera',
      'Etchings',
      'Figurines',
      'Glassware',
      'Handbooks and manuals',
      'Illustrations',
      'Implements, utensils, etc.',
      'Lithographs',
      'Manuscripts',
      'Maps',
      'Medical equipment & supplies',
      'Minutes (Records)',
      'Molecular models',
      'Money (Objects)',
      'Negatives',
      'Oral histories',
      'Paintings',
      'Pamphlets',
      'Personal correspondence',
      'Pesticides',
      'Photographs',
      'Photomechanical prints',
      'Plastics',
      'Portraits',
      'Postage stamps',
      'Press releases',
      'Prints',
      'Publications',
      'Rare books',
      'Sample books',
      'Scientific apparatus and instruments',
      'Slides',
      'Specimens',
      'Stereographs',
      'Textiles',
      'Vessels (Containers)',
      'Woodcuts'
    ].freeze

    DEPARTMENT = [
      'Archives',
      'Center for Oral History',
      'Museum',
      'Library',
    ]

    FILE_CREATOR = [
      'Brown, Will',
      'Center for Oral History',
      'Conservation Center for Art & Historic Artifacts',
      'DiMeo, Michelle',
      'George Blood Audio LP',
      'Kativa, Hillary',
      'Lockard, Douglas',
      'Lu, Cathleen',
      'Miller, Megan',
      'Muhlin, Jay',
      'Newhouse, Sarah',
      'The University of Pennsylvania Libraries',
      'Tobias, Gregory',
      'Voelkel, James',
    ]

    EXHIBITION = [
      "Age of Alchemy",
      "Books of Secrets",
      "Elemental Matters",
      "ExhibitLab",
      "Inspiring Youth in Chemistry",
      "Lobby 2017",
      "Making Modernity",
      "Marvels and Ciphers",
      "Molecules That Matter",
      "Object Explorer",
      "Science at Play",
      "Second Skin",
      "Sensing Change",
      "The Alchemical Quest",
      "The Sky's the Limit",
      "The Whole of Nature and the Mirror of Art",
      "Things Fall Apart",
      "Transmutations"
    ]

    PROJECT = [
      'Atmospheric Science',
      'Chemical History of Electronics',
      "Imagining Philadelphia's Energy Futures",
      'Mass Spectrometry',
      'Nanotechnology',
      'Oral History of the Toxic Substances Control Act',
      'Pew Biomedical Scholars',
      'REACH Ambler',
      'Scientific and Technical Information Systems',
      'Science and Disability',
    ]

  end
end

app/models/work/creator.rb
class Work
  class Creator
    CATEGORY_VALUES = %w{addressee after artist attributed_to author
                    contributor creator_of_work editor engraver interviewee
                    interviewer manufacturer manner_of photographer
                    printer printer_of_plates publisher school_of}

    include AttrJson::Model
    validates_presence_of :category, :value
    validates :category, inclusion:
      { in: CATEGORY_VALUES,
        allow_blank: true,
        message: "%{value} is not a valid category" }

    attr_json :category, :string
    attr_json :value, :string


  end
end

app/models/work/date.rb
class Work
  class Date
    include AttrJson::Model

    START_QUALIFIERS = %w{before after century circa decade undated}
    FINISH_QUALIFIERS = %w{before circa}

    validates :start_qualifier, inclusion: { in: START_QUALIFIERS, allow_blank: true }
    validates :finish_qualifier, inclusion: { in: FINISH_QUALIFIERS, allow_blank: true }
    validates_format_of :start, with: /\d{4}-\d{2}-\d{2}/, message: "must be of format YYYY-MM-DD"
    validates_format_of :finish, with: /\d{4}-\d{2}-\d{2}/, message: "must be of format YYYY-MM-DD", allow_blank: true



    attr_json :start, :string
    attr_json :start_qualifier, :string

    attr_json :finish, :string
    attr_json :finish_qualifier, :string

    attr_json :note, :string


  end
end

app/controllers/works_controller.rb
# FRONT-END controller for public Works views -- mostly just the #show action.
# Not to be confused with admin/works_controller for staff/management/edit views.
class WorksController < ApplicationController
  before_action :set_work, :check_auth

  def show
    respond_to do |format|
      format.html {
        render template: template
      }

      format.xml {
        render body: WorkOaiDcSerialization.new(@work).to_oai_dc, type: :xml
      }

      format.ris {
        send_data RisSerializer.new(@work).to_ris,
          disposition: 'attachment',
          filename: DownloadFilenameHelper.ris_download_name(@work),
          type: :ris
      }
    end
  end

  def viewer_images_info
    render json: ViewerMemberInfoSerializer.new(@work).as_hash
  end

  private

  def decorator
    @decorator ||= if has_audio_member?
      AudioWorkShowDecorator.new(@work)
    else
      WorkShowDecorator.new(@work)
    end
  end
  helper_method :decorator

  def has_audio_member?
    # some pg JSON operators in our WHERE clause to pull out actually just
    # what we want.
    #
    # The Decorators are going to fetch members again anyway, we're kind of fetching
    # content that will be fetched again -- but oh well, we do it nice and efficiently!
    #
    # We have to do two queries to get all the mime-types, one for where the direct member
    # is an asset, and another for where it's a child work and we have to follow leaf_representative
    #
    # We use Arel.sql cause if we don't we get a deprecation message telling us:
    #     "Dangerous query method... Known-safe values can be passed by wrapping them in Arel.sql()""
    @has_audio_member ||= begin
      direct_types = @work.members.
        where(published: true).
        distinct.pluck(Arel.sql("file_data -> 'metadata' -> 'mime_type'")).
        compact

      indirect_types = @work.members.
        where(published: true).
        joins(:leaf_representative).
        distinct.pluck(Arel.sql("leaf_representatives_kithe_models.file_data -> 'metadata' -> 'mime_type'")).
        compact

      (direct_types + indirect_types).any? { |t| t.start_with?("audio/")}
    end
  end

  def set_work
    @work = Work.find_by_friendlier_id!(params[:id])
  end

  def check_auth
    authorize! :read, @work
  end

  def template
    @template ||= decorator.view_template
  end

end

app/views/admin/works/_date_of_work.html.erb
<div class="form-row">
  <div class="col-left col-form-label">
    <%= f.label :start %>
  </div>
  <div class="col-sm">
    <%= f.input :start, label: false, placeholder: "YYYY-MM-DD" %>
  </div>
  <div class="col-sm">
    <%= f.input :start_qualifier, label: false, collection: Work::DateOfWork::START_QUALIFIERS %>
  </div>
</div>

<div class="form-row">
  <div class="col-left col-form-label">
    <%= f.label :finish %>
  </div>
  <div class="col-sm">
    <%= f.input :finish, label: false, placeholder: "YYYY-MM-DD" %>
  </div>
  <div class="col-sm">
    <%= f.input :finish_qualifier, label: false, collection: Work::DateOfWork::FINISH_QUALIFIERS %>
  </div>
</div>

<div class="form-row">
  <div class="col-left col-form-label">
    <%= f.label :note %>
  </div>
  <div class="col-sm">
    <%= f.input :note, label: false %>
  </div>
</div>

app/views/admin/works/edit.html.erb
<%= render 'form', work: @work %>

app/views/admin/works/index.html.erb
<h1>Works</h1>

<p>
  <%= link_to 'Create new work', new_admin_work_path, class: "btn btn-primary" %>
  <%= link_to 'Batch create works', admin_batch_create_path, class: "btn btn-outline-primary" %>
</p>

<%# this is ransack %>
<%= search_form_for [:admin, @q]  do |f| %>
  <div class="row">
    <div class="input-group col-sm-10 mb-3">
      <div class="input-group-prepend">
        <%= f.label :title_or_friendlier_id_cont, "In Title or ID", class: "input-group-text" %>
      </div>
      <%= f.search_field :title_or_friendlier_id_cont, class: "form-control" %>
      <div class="input-group-append">
        <%= f.button "Search", class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class="admin-filters">
    <div class="admin-filter">
      <label for="q_published">Published</label>
      <%= select_tag "q[published_eq]",
            options_for_select({"Yes" => true, "No" => false}, params[:q][:published_eq]),
            include_blank: "Any",
            class: "custom-select" %>
    </div>

    <div class="admin-filter">
      <label for="q_genre">Genre</label>
      <%= select_tag "q[genre]",
            options_for_select(Work::ControlledLists::GENRE, params[:q][:genre]),
            include_blank: "Any",
            class: "custom-select" %>
    </div>


    <div class="admin-filter">
        <label for="q_format">Format</label>
        <%= select_tag "q[format]",
              options_for_select(Work::ControlledLists::FORMAT.collect {|t| [t.titleize, t]}, params[:q][:format]),
              include_blank: "Any",
              class: "custom-select" %>
    </div>

    <div class="admin-filter">
        <label for="q_department">Department</label>
        <%= select_tag "q[department]",
              options_for_select(Work::ControlledLists::DEPARTMENT, params[:q][:department]),
              include_blank: "Any",
              class: "custom-select" %>
    </div>

    <div class="admin-filter">
      <label for="q_parent_id_null">Child Works In Results</label>
      <%= select_tag "q[parent_id_null]",
            options_for_select({"Yes" => "", "No" => true}, params[:q][:parent_id_null]),
            class: "custom-select"
      %>
    </div>
  </div>
<% end %>


<% if @works.total_count > 0 %>
  <p>
    <%= @works.offset_value + 1 %> - <%= @works.offset_value + @works.count %> of <%= @works.total_count %>
  </p>
<% end %>

<table class="table admin-list">
  <thead>
    <tr>
      <th class="thumbnail">thumbnail</th>
      <th class="id"><%= sort_link(@q, :id, "ID", page: nil) %></th>
      <th class="title"><%= sort_link(@q, :title, page: nil) %></th>
      <th class="datestamp"><%= sort_link(@q, :created_at, "Created", page: nil) %></th>
      <th class="datestamp"><%= sort_link(@q, :updated_at, "Last Modified", page: nil) %></th>
      <th class="action"></th>
      <th>Cart</th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= thumb_image_tag(work.leaf_representative, size: :mini, image_missing_text: true) %></td>
        <td><%= work.friendlier_id %></td>
        <td><%= link_to work.title, admin_work_path(work) %> <%= publication_badge(work) %></td>
        <td class="datestamp"><%= l work.created_at.to_date, format: :admin  %></td>
        <td class="datestamp"><%= l work.updated_at.to_date, format: :admin %></td>
        <td>
          <div class="dropdown">
            <a href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
            <%= admin_dropdown_for_work(work, labelled_by_id: "dropdownMenuButton") %>
          </div>
        </td>
        <td><%= CartControl.new(work.friendlier_id, cart_presence: @cart_presence, label_sr_only: true).display %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @works, theme: 'twitter-bootstrap-4' %>

app/views/admin/works/show.html.erb
  <div class="d-flex justify-content-between">

    <div>
      <div class="d-flex align-items-start mt-1">
        <% if @work.representative_id.present? %>
          <%= thumb_image_tag(@work.leaf_representative, size: :mini, image_missing_text: true, class: "mr-2") %>
        <% end %>
        <div>
          <div>Managing a Work</div>
          <h1><%= @work.title %> <%= publication_badge(@work) %>   <%= link_to "Public view", work_path(@work), class: "btn btn-sm btn-outline-primary" %></h1>
          <% if @work.parent.present? %>
            <p class="h4">Member in: <%= link_to "#{@work.parent.title} (#{@work.parent.friendlier_id})", admin_work_path(@work.parent) %></p>
          <% end %>
          <div>
            <%= CartControl.new(@work.friendlier_id, cart_presence: @cart_presence).display %>
          </div>
        </div>
      </div>
    </div>



    <div class="d-flex">
      <% if can? :publish, @work %>
        <div>
          <% if @work.published? %>
            <%= link_to "UN-Publish", unpublish_admin_work_path, method: "put", class: "btn btn-outline-danger" %>
          <% else %>
            <%= link_to "Publish", publish_admin_work_path, method: "put", class: "btn btn-danger" %>
          <% end %>
        </div>
      <% end %>

      <% if can? :destroy, @work %>
        <div>
          <div class="alert alert-secondary mx-1">
            <h2 class="h4 alert-heading">
              <a data-toggle="collapse" href="#deleteBtn1" role="button" aria-expanded="false" aria-controls="deleteBtn1">
                Delete
              </a>
            </h2>
            <div class="collapse" id="deleteBtn1">
                <%= link_to('Delete', [:admin, @work], method: :delete,
                     data: { confirm: "Delete Work '#{@work.title}'?" }, class: "btn btn-danger" )%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
</div>


<nav class="mb-2">
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-item nav-link active" id="nav-metadata-tab" data-toggle="tab" href="#nav-metadata" role="tab" aria-controls="nav-home" aria-selected="true">Metadata</a>
    <a class="nav-item nav-link" id="nav-members-tab" data-toggle="tab" href="#nav-members" role="tab" aria-controls="nav-profile" aria-selected="false">Members</a>

    <% if @work.genre && @work.genre.include?('Oral histories') %>
      <a class="nav-item nav-link" id="nav-oral-histories-tab" data-toggle="tab" href="#nav-oral-histories" role="tab" aria-controls="nav-profile" aria-selected="false">Oral History</a>
    <% end %>

  </div>
</nav>

<div class="tab-content">
  <div class="tab-pane show active" id="nav-metadata" role="tabpanel" aria-labelledby="nav-metadata-tab">

        <p>
          <%= link_to "Edit Metadata", edit_admin_work_path(@work), class: "btn btn-primary" %>
          <% if Admin::WorksController.can_demote_to_asset?(@work) %>
            <%= link_to "Demote to Asset",
                  demote_to_asset_admin_work_path(@work),
                  method: "put",
                  class: "btn btn-outline-primary",
                  data: { confirm: "All work metadata on #{@work.title} will be lost, this is not reversible. Are you sure?" } %>
          <% end %>
        </p>

        <%= render "metadata", work: @work %>

  </div>
  <div class="tab-pane" id="nav-members" role="tabpanel" aria-labelledby="nav-members-tab">
    <div class="admin-work-toolbar d-flex flex-wrap">
      <div class="alert alert-secondary mx-1">
        <h2 class="h4 alert-heading">Add New Members</h2>
        <% if @work.genre && @work.genre.include?('Oral histories') && @work.published? %>
          <small>Please unpublish this oral history if you want to add new audio segments.</small>
        <% else %>
        From:
          <%= link_to "Files", admin_asset_ingest_path(@work), class: "btn btn-primary" %>
          <%= link_to "New Child Work", new_admin_work_path(parent_id: @work), class: "btn btn-primary" %>
        <% end %>
      </div>

      <div class="alert alert-secondary mx-1">
        <h2 class="h4 alert-heading">Re-order Members</h2>

        <% if @work.genre && @work.genre.include?('Oral histories') && @work.published? %>
          <small>Please unpublish this oral history if you want to reorder its segments.</small>
        <% else %>
        <%= link_to "Manual", reorder_members_admin_work_path(@work), class: "btn btn-primary" %>
        <%= link_to "Alphabetical", reorder_members_admin_work_path(@work), method: "put", class: "btn btn-primary", data: { confirm: "Re-ordering members alphabetically by title can't be undone" } %>
        <% end %>

      </div>
    </div>

    <p><%= @work.members.count  %> members</p>

    <%= render "member_list_table", work: @work %>
  </div>

  <% if @work.genre && @work.genre.include?('Oral histories') %>



    <div class="tab-pane" id="nav-oral-histories" role="tabpanel" aria-labelledby="nav-oral-histories-tab">

      <%= WorkCombinedAudioDerivatives.new(@work).display %>

      <div class="card bg-light mb-3">
        <h2 class="card-header h3">OHMS XML attached</h2>
        <div class="card-body">
          <dl class="row">
            <% if @work.oral_history_content!.ohms_xml.present? %>
              <dt class="col-sm-6">attached?</dt><dd class="col-sm-6"><span class="text-success font-weight-bold">YES</span></dd>
              <dt class="col-sm-6">id</dt><dd class="col-sm-6"><%= @work.oral_history_content!.ohms_xml.record_id %></dd>
              <dt class="col-sm-6">dt</dt><dd class="col-sm-6"><%= @work.oral_history_content!.ohms_xml.record_dt %></dd>
              <dt class="col-sm-6">accession</dt><dd class="col-sm-6"><%= @work.oral_history_content!.ohms_xml.accession %></dd>
            <% else %>
              <dt class="col-sm-6">attached?</dt><dd class="col-sm-6"><span class="text-danger font-weight-bold">NO</span></dd>
            <% end %>
          </dl>
          <hr>
          <h3 class="h4">Upload New OHMS XML file</h3>
          <%= form_with(url: submit_ohms_xml_admin_work_path(@work), local: true, multipart: true, method: :put) do %>
            <%= file_field_tag 'ohms_xml', accept: "application/xml" %>
            <%= submit_tag "Upload", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>