config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  class LoggedInConstraint
    def self.matches?(request)
      current_user = request.env['warden'].user
      !!current_user
    end
  end

  root 'homepage#index'

  match 'oai', to: "oai_pmh#index", via: [:get, :post], as: :oai_provider

  # https://github.com/plataformatec/devise/wiki/how-to:-change-the-default-sign_in-and-sign_out-routes
  # We aren't using :registration cause we don't want to allow self-registration,
  # We aren't using session cause we define em ourselves manually.
  devise_for :users, skip: [:session, :registration]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Dynamic robots.txt
  # this will fall through to ./views/application/robots.txt.erb, no need for an action method
  get 'robots.txt', to: "application#robots.txt", format: "text"

  # On-demand derivatives
  constraints(derivative_type: Regexp.union(OnDemandDerivative.derivative_type_definitions.keys.collect(&:to_s))) do
    get "works/:id/:derivative_type", to: "on_demand_derivatives#on_demand_status", as: :on_demand_derivative_status
  end

  # public-facing routes
  resources :works, only: [:show]

  # JSON info for scihist_viewer image viewer
  get '/works/:id/viewer_images_info' => 'works#viewer_images_info',
    defaults: {format: "json"},
    format: false,
    as: :viewer_images_info

  # Make the viewer  URL lead to ordinary show page, so JS can pick it up and launch viewer.
  get '/works/:id/viewer/:viewer_member_id(.:format)' => 'works#show', as: :viewer


  get '/collections', to: "collections_list#index", as: :collections

  # Our collections show controller provides a Blacklight search, so needs
  # some additional routes for various search behaviors too.
  get "/collections/:collection_id", to: "collection_show#index", as: :collection
  get "collections/:collection_id/range_limit" => "collection_show#range_limit"
  get "collections/:collection_id/range_limit_panel" => "collection_show#range_limit_panel"
  get "collections/:collection_id/facet" => "collection_show#facet"

  get "focus/:slug", to: "featured_topic#index", as: :featured_topic
  get "focus/:slug/range_limit" => "featured_topic#range_limit"
  get "focus/:slug/range_limit_panel" => "featured_topic#range_limit_panel"
  get "focus/:slug/facet" => "featured_topic#facet"


  # download_path(asset)
  # download_url(asset)
  get "downloads/:asset_id", to: "downloads#original", as: :download
  # download_derivative_path(asset, "thumb_small")
  # download_derivative_url(asset, "thumb_small")
  get "downloads/:asset_id/:derivative_key", to: "downloads#derivative", as: :download_derivative


  ##
  # Blacklight-generated routes, that were then modified a bit by us to take
  # out stuff we're not using.
  #

      # Route RSS and atom search results to a 404
      # until we decide to implement them.
      # Practically speaking, this only affects bots).
      get 'catalog.rss',  to: proc { [404, {}, ['']] }
      get 'catalog.atom', to: proc { [404, {}, ['']] }
      get 'catalog.json', to: proc { [404, {}, ['']] }

      # TODO: Can we get away without actuallymounting Blacklight, just using the CatalogController?
      # mount Blacklight::Engine => '/'
      concern :searchable, Blacklight::Routes::Searchable.new
      resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
        concerns :searchable
        concerns :range_searchable # for blacklight_range_limit
      end

      # We aren't using default Blacklight action for 'show' item, instead using our
      # own ActiveRecord-model based show, so don't need to route SolrDocumentController...
      # we think, at least for now.
      #
      # concern :exportable, Blacklight::Routes::Exportable.new
      # resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
      #   concerns :exportable
      # end

      # We aren't using bookmarks, and don't have to route them
      # --jrochkind
      # resources :bookmarks do
      #   concerns :exportable

      #   collection do
      #     delete 'clear'
      #   end
      # end
  ##
  # End Blacklight-generated routes
  ##

  # Routes will even only _show up_ to logged in users, this applies
  # to internal rack apps we're mounting here too, like shrine upload endpoints,
  # is one reason to use a constraint.
  namespace :admin do
    root to: "works#index"

    resources :users, except: [:destroy, :show] do
      member do
        post "send_password_reset"
      end
    end

    # Admin page for work management, we'll handle public view elsewhere
    resources :works do
      member do
        get "reorder_members", to: "works#reorder_members_form"
        put "reorder_members"
        put "demote_to_asset"
        put "publish"
        put "unpublish"
        put "submit_ohms_xml"
        put "create_combined_audio_derivatives"
      end
      collection do
        get 'batch_update', to: "works#batch_update_form"
        post 'batch_update'
      end
    end

    get "/works/:parent_id/ingest", to: "assets#display_attach_form", as: "asset_ingest"
    post "/works/:parent_id/ingest", to: "assets#attach_files"


    resources :collections, except: [:show]

    # Note "assets" is Rails reserved word for routing, oops. So we use
    # asset_files.
    resources :assets, path: "asset_files", except: [:new, :create] do
      member do
        put "convert_to_child_work"
      end
    end

    post "/asset_files/:asset_id/check_fixity", to: "assets#check_fixity", as: "check_fixity"
    get "/fixity_report", to: "assets#fixity_report", as: "fixity_report"

    get "/batch_create", to: "batch_create#new", as: "batch_create" # step 1
    post "/batch_create", to: "batch_create#add_files" # step 2
    post "/batch_create/finish", to: "batch_create#create" # step 3, create and redirect

    resources :digitization_queue_items, except: [:index, :create, :new, :destroy] do
      collection do
        get "collecting_areas"

        # index, new and create need a /$collecting_area on them.
        constraints(proc {|params, req|
            Admin::DigitizationQueueItem::COLLECTING_AREAS.include?(params[:collecting_area])
        }) do
          get ":collecting_area", to: "digitization_queue_items#index", as: ""
          post ":collecting_area", to: "digitization_queue_items#create", as: nil
          get ":collecting_area/new", to: "digitization_queue_items#new", as: "new"
        end
      end
      member do
        post :add_comment
      end
    end

    resources :r_and_r_items do
      member do
        post :add_comment
      end
    end

    delete  "digitization_queue_items/:id/delete_comment/:comment_id",
      to: "digitization_queue_items#delete_comment",
      as: "delete_digitization_queue_item_comment"

    delete  "r_and_r_items/:id/delete_comment/:comment_id",
      to: "r_and_r_items#delete_comment",
      as: "delete_r_and_r_comment"

    resources :cart_items, param: :work_friendlier_id, only: [:index, :update, :destroy] do
      collection do
        delete 'clear'
      end
    end


    # These 'sub-apps' are for admin-use only, but since they are sub-apps
    # aren't protected by the AdminController. We have Rails routing only
    # provide the routes if there is a logged-in user.
    constraints LoggedInConstraint do
      mount Resque::Server, at: '/queues'

      mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", as: :direct_app_upload

      if Shrine.storages[:cache].kind_of?(Shrine::Storage::S3)
        mount Shrine.uppy_s3_multipart(:cache) => "/s3"
      end
    end
  end

  # We can't put browse-everything in the routing namespace, cause it breaks
  # browse-everything, alas. We'll still make it route as if it were, and
  # add a routing constraint to protect to just logged in users.
  constraints LoggedInConstraint do
    mount BrowseEverything::Engine => '/admin/browse'

    # Don't know if we really need qa to be limited to logged-in users, but
    # that's the only place we use it, so let's limit to avoid anyone DOSing
    # us with it or whatever.
    #
    # And we mount it as '/authorities' rather than '/qa' that the installer
    # wanted, to match sufia/hyrax and be less weird.
    mount Qa::Engine => '/authorities'
  end


  # Tell Rails polymorphic routing to assume :admin namespace for works,
  # so we can just do `url_for @work` and get /admin/works.
  #
  # May not actually be a good idea? What will we do when we add non-admin show?
  resolve("Work") do |work, options|
    [:admin, work, options]
  end
  resolve("Asset") do |asset, options|
    [:admin, asset, options]
  end
  resolve("Collection") do |collection, options|
    [:admin, collection, options]
  end

  #Static pages
  %w(about contact faq policy).each do |page_label|
    get page_label, controller: 'static', action: page_label, as: page_label
  end

end

app/models/collection.rb
# A collection thumbnail is stored as an Asset, which has the collection as it's parent (not any work),
# and is set as the collections #representative too.
#
# Since the member relation destroys children when parent is deleted, deleting a collection
# automatically deletes the thumb (which automatically deletes the stored file)
class Collection < Kithe::Collection
  # automatic Solr indexing on save
  self.kithe_indexable_mapper = CollectionIndexer.new

  validates :related_url, array_inclusion: {
    proc: ->(v) { ScihistDigicoll::Util.valid_url?(v) } ,
    message: "is not a valid url: %{rejected_values}"
  }

  accepts_nested_attributes_for :representative

  attr_json :description, :text
  attr_json :related_url, :string, array: true

  # Override the default ActiveRecord one to create a new Asset if it didn't exist already.
  # The default AR didn't work quite right because of STI and other reasons, but this works
  # nicely, if representative_attributes come form form and a representative doesn't exist
  # already, it'll create one, with this collection as a parent, and set to this collection's
  # representative -- that'll all be automatically saved iff the collection is succesfully saved.
  #
  # If there already was a representative, still works.
  #
  # We also set the asset title to the file title, if appropriate.
  def representative_attributes=(attributes)
    if representative.nil?
      build_representative
    end
    self.representative.assign_attributes(attributes)

    if filename = representative.file&.try(:metadata).try(:[], :filename)
      representative.title = filename
    end
  end

  def build_representative
    self.representative = CollectionThumbAsset.new(title: "collection-thumbnail-placeholder", parent: self)
  end
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < AdminController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)
    respond_to do |format|
      if @collection.save
        format.html { redirect_to admin_collections_url, notice: "Collection '#{@collection.title}' was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to admin_collections_url, notice: "Collection '#{@collection.title}' was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    authorize! :destroy, @collection

    @collection.destroy
    respond_to do |format|
      format.html { redirect_to admin_collections_url, notice: "Collection '#{@collection.title}' was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find_by_friendlier_id!(params[:id])
    end

    # only allow whitelisted params through (TODO, we're allowing all collection params!)
    # Plus sanitization or any other mutation.
    #
    # This could be done in a form object or otherwise abstracted, but this is good
    # enough for now.
    def collection_params
      permitted_attributes = [:title, :description]
      permitted_attributes << :published if can?(:publish, @collection || Collection)

      params.
        require(:collection).
        permit(*permitted_attributes, :representative_attributes => {}, :related_url_attributes => []).tap do |hash|
          # sanitize description
          if hash[:description].present?
            hash[:description] = DescriptionSanitizer.new.sanitize(hash[:description])
          end
        end
    end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collections_path, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collections_path, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find_by_friendlier_id(params[:id])
    end

    # only allow whitelisted params through (TODO, we're allowing all collection params!)
    # Plus sanitization or any other mutation.
    #
    # This could be done in a form object or otherwise abstracted, but this is good
    # enough for now.
    def collection_params
      params.require(:collection).permit!
    end
end

app/views/admin/collections/_form.html.erb
<%= kithe_form_for([:admin, collection], :html=> { novalidate: true, class: 'edit-collection mx-auto admin-edit' }) do |f| %>
  <div class="admin-header sticky-top d-flex justify-content-between p-2 mb-4 mt-1 bg-light border">
    <div class="form-actions-label">
      <h1 class="h4">
        <% if @collection.persisted? %>
          Editing <%= @collection.title %> (<%= @collection.friendlier_id %>)
        <% else %>
          New Collection
        <% end %>
      </h1>
    </div>

    <div class="form-actions">
      <%= link_to 'Cancel', admin_collections_url, class: "btn btn-outline-primary" %>
      <%= f.button :submit %>
    </div>
  </div>

  <% if collection.errors.any? %>
    <div class="kithe-form-errors-top alert alert-danger mb-4" role="alert"">
      <h2 class="h4" class="alert-heading"><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved</h2>
      <ol class="mb-0">
      <% collection.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    </div>
  <% end %>

  <div class="form-inputs">
    <%= f.input :title %>

    <%= f.input :description, as: :text, input_html: { rows: 14 } %>

    <% if can? :publish, collection %>
      <%= f.input :published %>
    <% end %>

    <%= f.repeatable_attr_input :related_url, build: :at_least_one %>


    <%# uppy simple file input heavily adapted from shrine-rails-example single "cover" photo.
        https://github.com/erikdahlstrand/shrine-rails-example

        Goes with javascript in simple_uppy_file_input.js
    -%>
    <div class="form-group form-group-valid">
      <label class="form-control-label string" for="collection_thumbnail">Thumbnail</label>
      <small class="form-text text-muted scihist-hint mb-2 mt-0">Image for collection, should be <b>square and at least
        <%= CollectionThumbAsset::COLLECTION_PAGE_THUMB_SIZE * 2 %>x<%= CollectionThumbAsset::COLLECTION_PAGE_THUMB_SIZE * 2%> pixels</b>. No need to resize—full-size crop is great for possible future uses.</small>

      <%= f.fields_for :representative, (f.object.representative || f.object.build_representative) do |representative_f| %>

        <%= representative_f.hidden_field :file,
                value: collection&.representative&.cached_file_data,
                id: "collection-thumbnail-upload-result",
                data: {
                  toggle: "scihist-simple-uppy-file-hidden"
                }
        %>
        <%= representative_f.file_field :file,
              id: "collection_thumbnail",
              accept: "image/*",
              data: {
                upload_server: "",
                preview_element: "preview-cover-photo",
                upload_result_element: "album-cover-photo-upload-result"
              }.merge(UploadUtil.kithe_upload_data_config(toggle_value: "scihist-simple-uppy-file"))
        %>
        <div class="image-preview mb-2" data-toggle="scihist-simple-uppy-file-preview">
          <% if collection.representative.cached_file_data  %>
            <p>Will be saved: <%= collection.representative.original_filename %></p>
          <% elsif collection.representative.file.present? %>
            <%= thumb_image_tag(collection.leaf_representative, size: :collection_page, image_missing_text: true) %>

            <br><i><%= collection.representative.title %></i>

            <% if collection.representative.file &&
              ( !collection.representative.content_type.start_with?("image/") ||
                collection.representative.width != collection.representative.height ||
              collection.representative.width < 532 ) %>
              <p class="text-danger small">Uploaded asset should be a square image at least of at least <%= CollectionThumbAsset::COLLECTION_PAGE_THUMB_SIZE * 2%> pixels.
                The saved file type <%= collection.representative.content_type %>,
                <%= collection.representative.width %>x<%= collection.representative.height %>px. It is recommended
                you upload a different file, of appropriate dimensions.
              </p>
            <% end %>

          <% end %>
        </div>
      <% end %>
    </div>


  </div>
<% end %>

app/views/admin/collections/edit.html.erb
<%= render 'form', collection: @collection %>

app/views/admin/collections/index.html.erb
<h1>Collections</h1>

<%= link_to 'New Collection', new_admin_collection_path, class: "btn btn-primary" %>

<table class="table mt-4">
  <thead>
    <tr>
      <th>thumbnail</th>
      <th>ID</th>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= thumb_image_tag(collection.leaf_representative, size: :mini, image_missing_text: true) %>
        <td><%= collection.friendlier_id %>
        <td><%= collection.title %> <%= publication_badge(collection) %></td>
        <td>
          <%= link_to 'Public view', collection_path(collection), class: "btn btn-sm btn-outline-primary" %>
          <%= link_to 'Edit', edit_admin_collection_path(collection), class: "btn btn-sm btn-outline-primary" %>
          <% if can? :destroy, collection %>
            <%= link_to 'Delete', [:admin, collection], method: :delete, data: { confirm: "Delete collection '#{collection.title}'?" }, class: "btn btn-sm btn-outline-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/collections/new.html.erb
<%= render 'form', collection: @collection %>