config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  class LoggedInConstraint
    def self.matches?(request)
      current_user = request.env['warden'].user
      !!current_user
    end
  end

  root 'homepage#index'

  match 'oai', to: "oai_pmh#index", via: [:get, :post], as: :oai_provider

  # https://github.com/plataformatec/devise/wiki/how-to:-change-the-default-sign_in-and-sign_out-routes
  # We aren't using :registration cause we don't want to allow self-registration,
  # We aren't using session cause we define em ourselves manually.
  devise_for :users, skip: [:session, :registration]
  devise_scope :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Dynamic robots.txt
  # this will fall through to ./views/application/robots.txt.erb, no need for an action method
  get 'robots.txt', to: "application#robots.txt", format: "text"

  # On-demand derivatives
  constraints(derivative_type: Regexp.union(OnDemandDerivative.derivative_type_definitions.keys.collect(&:to_s))) do
    get "works/:id/:derivative_type", to: "on_demand_derivatives#on_demand_status", as: :on_demand_derivative_status
  end

  # public-facing routes
  resources :works, only: [:show]

  # JSON info for scihist_viewer image viewer
  get '/works/:id/viewer_images_info' => 'works#viewer_images_info',
    defaults: {format: "json"},
    format: false,
    as: :viewer_images_info

  # Make the viewer  URL lead to ordinary show page, so JS can pick it up and launch viewer.
  get '/works/:id/viewer/:viewer_member_id(.:format)' => 'works#show', as: :viewer


  get '/collections', to: "collections_list#index", as: :collections

  # Our collections show controller provides a Blacklight search, so needs
  # some additional routes for various search behaviors too.
  get "/collections/:collection_id", to: "collection_show#index", as: :collection
  get "collections/:collection_id/range_limit" => "collection_show#range_limit"
  get "collections/:collection_id/range_limit_panel" => "collection_show#range_limit_panel"
  get "collections/:collection_id/facet" => "collection_show#facet"

  get "focus/:slug", to: "featured_topic#index", as: :featured_topic
  get "focus/:slug/range_limit" => "featured_topic#range_limit"
  get "focus/:slug/range_limit_panel" => "featured_topic#range_limit_panel"
  get "focus/:slug/facet" => "featured_topic#facet"


  # download_path(asset)
  # download_url(asset)
  get "downloads/:asset_id", to: "downloads#original", as: :download
  # download_derivative_path(asset, "thumb_small")
  # download_derivative_url(asset, "thumb_small")
  get "downloads/:asset_id/:derivative_key", to: "downloads#derivative", as: :download_derivative


  ##
  # Blacklight-generated routes, that were then modified a bit by us to take
  # out stuff we're not using.
  #

      # Route RSS and atom search results to a 404
      # until we decide to implement them.
      # Practically speaking, this only affects bots).
      get 'catalog.rss',  to: proc { [404, {}, ['']] }
      get 'catalog.atom', to: proc { [404, {}, ['']] }
      get 'catalog.json', to: proc { [404, {}, ['']] }

      # TODO: Can we get away without actuallymounting Blacklight, just using the CatalogController?
      # mount Blacklight::Engine => '/'
      concern :searchable, Blacklight::Routes::Searchable.new
      resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
        concerns :searchable
        concerns :range_searchable # for blacklight_range_limit
      end

      # We aren't using default Blacklight action for 'show' item, instead using our
      # own ActiveRecord-model based show, so don't need to route SolrDocumentController...
      # we think, at least for now.
      #
      # concern :exportable, Blacklight::Routes::Exportable.new
      # resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
      #   concerns :exportable
      # end

      # We aren't using bookmarks, and don't have to route them
      # --jrochkind
      # resources :bookmarks do
      #   concerns :exportable

      #   collection do
      #     delete 'clear'
      #   end
      # end
  ##
  # End Blacklight-generated routes
  ##

  # Routes will even only _show up_ to logged in users, this applies
  # to internal rack apps we're mounting here too, like shrine upload endpoints,
  # is one reason to use a constraint.
  namespace :admin do
    root to: "works#index"

    resources :users, except: [:destroy, :show] do
      member do
        post "send_password_reset"
      end
    end

    # Admin page for work management, we'll handle public view elsewhere
    resources :works do
      member do
        get "reorder_members", to: "works#reorder_members_form"
        put "reorder_members"
        put "demote_to_asset"
        put "publish"
        put "unpublish"
        put "submit_ohms_xml"
        put "create_combined_audio_derivatives"
      end
      collection do
        get 'batch_update', to: "works#batch_update_form"
        post 'batch_update'
      end
    end

    get "/works/:parent_id/ingest", to: "assets#display_attach_form", as: "asset_ingest"
    post "/works/:parent_id/ingest", to: "assets#attach_files"


    resources :collections, except: [:show]

    # Note "assets" is Rails reserved word for routing, oops. So we use
    # asset_files.
    resources :assets, path: "asset_files", except: [:new, :create] do
      member do
        put "convert_to_child_work"
      end
    end

    post "/asset_files/:asset_id/check_fixity", to: "assets#check_fixity", as: "check_fixity"
    get "/fixity_report", to: "assets#fixity_report", as: "fixity_report"

    get "/batch_create", to: "batch_create#new", as: "batch_create" # step 1
    post "/batch_create", to: "batch_create#add_files" # step 2
    post "/batch_create/finish", to: "batch_create#create" # step 3, create and redirect

    resources :digitization_queue_items, except: [:index, :create, :new, :destroy] do
      collection do
        get "collecting_areas"

        # index, new and create need a /$collecting_area on them.
        constraints(proc {|params, req|
            Admin::DigitizationQueueItem::COLLECTING_AREAS.include?(params[:collecting_area])
        }) do
          get ":collecting_area", to: "digitization_queue_items#index", as: ""
          post ":collecting_area", to: "digitization_queue_items#create", as: nil
          get ":collecting_area/new", to: "digitization_queue_items#new", as: "new"
        end
      end
      member do
        post :add_comment
      end
    end

    resources :r_and_r_items do
      member do
        post :add_comment
      end
    end

    delete  "digitization_queue_items/:id/delete_comment/:comment_id",
      to: "digitization_queue_items#delete_comment",
      as: "delete_digitization_queue_item_comment"

    delete  "r_and_r_items/:id/delete_comment/:comment_id",
      to: "r_and_r_items#delete_comment",
      as: "delete_r_and_r_comment"

    resources :cart_items, param: :work_friendlier_id, only: [:index, :update, :destroy] do
      collection do
        delete 'clear'
      end
    end


    # These 'sub-apps' are for admin-use only, but since they are sub-apps
    # aren't protected by the AdminController. We have Rails routing only
    # provide the routes if there is a logged-in user.
    constraints LoggedInConstraint do
      mount Resque::Server, at: '/queues'

      mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", as: :direct_app_upload

      if Shrine.storages[:cache].kind_of?(Shrine::Storage::S3)
        mount Shrine.uppy_s3_multipart(:cache) => "/s3"
      end
    end
  end

  # We can't put browse-everything in the routing namespace, cause it breaks
  # browse-everything, alas. We'll still make it route as if it were, and
  # add a routing constraint to protect to just logged in users.
  constraints LoggedInConstraint do
    mount BrowseEverything::Engine => '/admin/browse'

    # Don't know if we really need qa to be limited to logged-in users, but
    # that's the only place we use it, so let's limit to avoid anyone DOSing
    # us with it or whatever.
    #
    # And we mount it as '/authorities' rather than '/qa' that the installer
    # wanted, to match sufia/hyrax and be less weird.
    mount Qa::Engine => '/authorities'
  end


  # Tell Rails polymorphic routing to assume :admin namespace for works,
  # so we can just do `url_for @work` and get /admin/works.
  #
  # May not actually be a good idea? What will we do when we add non-admin show?
  resolve("Work") do |work, options|
    [:admin, work, options]
  end
  resolve("Asset") do |asset, options|
    [:admin, asset, options]
  end
  resolve("Collection") do |collection, options|
    [:admin, collection, options]
  end

  #Static pages
  %w(about contact faq policy).each do |page_label|
    get page_label, controller: 'static', action: page_label, as: page_label
  end

end

app/controllers/admin/r_and_r_items_controller.rb
# This controller is based on Admin::DigitizationQueueItemsController.rb
class Admin::RAndRItemsController < AdminController
  before_action :set_admin_r_and_r_item, only: [:show, :edit, :update, :destroy, :add_comment, :delete_comment]

  # GET /admin/r_and_r_items
  # GET /admin/r_and_r_items.json
  def index
    @admin_r_and_r_items = filtered_index_items
  end

  # GET /admin/r_and_r_items/1
  # GET /admin/r_and_r_items/1.json
  def show
  end

  # GET /admin/r_and_r_items/new
  def new
    @admin_r_and_r_item = Admin::RAndRItem.new
  end

  # GET /admin/r_and_r_items/1/edit
  def edit
  end

  # POST /admin/r_and_r_items/create
  # POST /admin/r_and_r_items/create.json
  def create
    @admin_r_and_r_item = Admin::RAndRItem.new(admin_r_and_r_item_params)
    respond_to do |format|
      if @admin_r_and_r_item.save
        format.html { redirect_to admin_r_and_r_item_path(@admin_r_and_r_item), notice: 'R&R item was successfully created.' }
        format.json { render :show, status: :created, location: admin_r_and_r_items_url(@admin_r_and_r_item.collecting_area) }
      else
        format.html { render :new }
        format.json { render json: @admin_r_and_r_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/r_and_r_items/1
  # PATCH/PUT /admin/r_and_r_items/1.json
  def update
    respond_to do |format|
      if update_with_action_comments(@admin_r_and_r_item, admin_r_and_r_item_params)
        notice = 'R&R item updated.'
        format.html { redirect_to @admin_r_and_r_item, notice: notice }
        format.json { render json: { notice: notice } }
      else
        format.html { render :edit }
        format.json { render json: @admin_r_and_r_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/r_and_r_items/1
  # DELETE /admin/r_and_r_items/1.json
  def destroy
    @admin_r_and_r_item.destroy
    respond_to do |format|
      format.html { redirect_to admin_r_and_r_items_url, notice: "#{@admin_r_and_r_item.title} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def collecting_area
    @admin_r_and_r_item.try(:collecting_area) # || params.fetch(:collecting_area)
  end
  helper_method :collecting_area



  # POST /admin/r_and_r_item/1/add_comment
  def add_comment
    if params["comment"].present?
      Admin::QueueItemComment.create!(
        user: current_user,
        r_and_r_item: @admin_r_and_r_item,
        text: params["comment"]
      )
    end
    redirect_to @admin_r_and_r_item
  end

  # admin_delete_comment
  # DELETE
  # /admin/r_and_r_items/:id/delete_comment/:comment_id(.:format)
  # admin/digitization_queue_items#delete_comment
  def delete_comment
    comment = Admin::QueueItemComment.find_by_id(params['comment_id'])
    raise ArgumentError.new( 'Could not find this comment.') if comment.nil?
    if can?(:destroy, comment)
      comment.delete
      notice = 'Comment deleted.'
    else
      notice = 'You may not delete this comment.'
    end
    redirect_to @admin_r_and_r_item,
      notice: notice
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_admin_r_and_r_item
    @admin_r_and_r_item = Admin::RAndRItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def admin_r_and_r_item_params
    params.require(:admin_r_and_r_item).permit(
      :title, :status, :accession_number, :museum_object_id, :bib_number, :location,
      :box, :folder, :dimensions, :materials, :copyright_status,
      :scope, :instructions, :additional_notes, :collecting_area,
      :is_destined_for_ingest, :copyright_research_still_needed, :curator, :patron_name,
      :patron_email, :deadline, :date_files_sent,
      :additional_pages_to_ingest, :status_changed_at
    )
  end

  def filtered_index_items
    scope = Admin::RAndRItem.order(deadline: :asc)

    if (q = params.dig(:query, :q)).present?
      scope = scope.where("title like ? OR bib_number = ? or accession_number = ? OR museum_object_id = ?", "%#{q}%", q, q, q)
    end

    status = params.dig(:query, :status)

    if status == "ANY"
      # no-op, no filter
    elsif status.blank? # default, "open"
      scope = scope.open_status
    else
      scope = scope.where(status: status)
    end

    collecting_area = params.dig(:query, :collecting_area)
    unless collecting_area.blank? || collecting_area == "ANY"
      scope = scope.where(collecting_area: collecting_area)
    end

    scope.page(params[:page]).per(100)
  end

  # hacky helper to give us select menu options for status filter
  #
  # The 'nil' option is actually 'closed', that we want to be default
  def status_filter_options
    helpers.options_for_select([["Any", "ANY"]], params.dig(:query, :status)) +
    helpers.grouped_options_for_select(
      { "open/closed" => [["Open", ""], ["Closed", "closed"]],
        "status" =>  Admin::RAndRItem::STATUSES.
          find_all {|s| s != "closed" }.
          collect {|s| [s.humanize, s]}
      },
      params.dig(:query, :status) || ""
    )
  end
  helper_method :status_filter_options

  def collecting_area_filter_options
    helpers.options_for_select([["Any", "ANY"]], params.dig(:query, :status)) +
    helpers.grouped_options_for_select(
      { "collecting area" =>  Admin::RAndRItem::COLLECTING_AREAS.
          collect {|s| [s.humanize, s]}
      },
      params.dig(:query, :collecting_area) || ""
    )
  end
  helper_method :collecting_area_filter_options

  def update_with_action_comments(queue_item, params)
    result = nil
    queue_item.class.transaction do
      result = queue_item.update(params)
      if result && queue_item.saved_change_to_status?
        queue_item.queue_item_comments.create!(system_action: true, user: current_user, text: "marked: #{queue_item.status.humanize.downcase}")
      end
    end
    result
  end
end

app/views/admin/r_and_r_items/_form.html.erb
<%= simple_form_for(@admin_r_and_r_item) do |f| %>
  <% if @admin_r_and_r_item.errors.any? %>

    <div class="kithe-form-errors-top alert alert-danger mb-4" role="alert">
      <h2 class="h4" class="alert-heading"><%= pluralize(@admin_r_and_r_item.errors.count, "error") %> prohibited this work from being saved</h2>
      <ol class="mb-0">
        <% @admin_r_and_r_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ol>
    </div>
  <% end %>

  <div class="form-inputs">

    <div class="row">
      <div class="col">
        <%= f.input :title%>
      </div>
      <div class="col">
        <%= f.input :is_destined_for_ingest,
        label: "Ingest this item ?",
        hint: "Check this box if we also want this item in the Digital Collections."
      %>
      </div>
      <div class="col">
        <%= f.input :copyright_research_still_needed,
        label: "Copyright research still needed",
        hint: "Uncheck this to indicate copyright research is complete."
      %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :curator,
          label: "Curator",
          hint: "Who is fielding this request?"
        %>
      </div>
      <div class="col">
        <%= f.input :patron_name,
          hint: "The person who requested the item(s) be digitized.",
          label: "Patron name" %>
      </div>
      <div class="col">
        <%= f.input :patron_email,
          hint: "That person's email.",
          label: "Patron email" %>
      </div>
    </div>


    <div class="row">
      <div class="col">
        <%= f.input :status,
          label: "R&R Status",
          collection: Admin::RAndRItem::STATUSES.collect {|s| [s.humanize, s]},
          include_blank: false %>
      </div>
        <div class="col">
        <%= f.input :collecting_area,
        label: "Collecting area",
        collection: Admin::RAndRItem::COLLECTING_AREAS.collect {|s| [s.humanize, s]},
        include_blank: false
        %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :deadline,
          as: :date, html5: true,
          label: "Deadline", hint: "Send files to patron by this date." %>
      </div>
      <div class="col">
        <%= f.input :date_files_sent,
        as: :date, html5: true,
        label: "Date sent", hint: "When the files were actually sent to the patron. Leave blank until actually sent."  %>
      </div>
    </div>


    <div class="row">
      <div class="col">
        <%= f.input :accession_number %>
      </div>
      <div class="col">
        <%= f.input :museum_object_id, label: "Object ID (Past Perfect)" %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :bib_number, hint: "if applicable" %>
      </div>
      <div class="col">
        <%= f.input :location, hint: "Call number, Home Location, etc." %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :box %>
      </div>
      <div class="col">
        <%= f.input :folder %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :dimensions %>
      </div>
      <div class="col">
        <%= f.input :materials %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :scope, label: "Scope", hint: "Pages to digitize for R&R only" %>
      </div>
        <div class="col">
        <%= f.input :additional_pages_to_ingest, label: "Additional pages or images", hint: "Only for the Digital Collections. Do not send these to the patron." %>
      </div>
      <div class="col">
        <%= f.input :instructions, hint: "Staging notes, handling instructions, etc." %>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <%= f.input :copyright_status, as: :text %>
      </div>
      <div class="col">
        <%= f.input :additional_notes, label: "Additional notes <small>(shows up on list view)</small>".html_safe %>
      </div>
    </div>
  </div>

  <div class="form-actions mb-3">
    <%= link_to "Cancel", admin_r_and_r_items_path(collecting_area), class: "btn btn-outline-primary" %>
    <%= f.button :submit, value: "#{f.object.new_record? ? 'Create' : 'Update'}" %>
  </div>
</div>
<% end %>

app/views/admin/r_and_r_items/edit.html.erb
<h1>Editing R&amp;R Item</h1>

<%= render 'form', admin_r_and_r_item: @admin_r_and_r_item %>

app/views/admin/r_and_r_items/index.html.erb
<h1>Rights and Reproductions</h1>


<p>
  <%= link_to 'New R & R Item', new_admin_r_and_r_item_path, class: "btn btn-primary" %>
</p>


<div class="my-2">
  <%#= simple_form_for(:query, url: admin_digitization_queue_item_path(collecting_area), method: :get) do |f| %>
  <%= simple_form_for(:query, url: admin_r_and_r_items_path, method: :get) do |f| %>
    <div class="row form-group">
      <div class="col-sm-10">
        <small class="text-muted">Title, or ID (bib, accession, or object)</small>
      </div>
      <div class="input-group col-sm-10">
        <div class="input-group-prepend">
          <%= f.label :q, "Search", class: "input-group-text" %>
        </div>
        <%= f.search_field :q, class: "form-control", value: params.dig(:query, :q) %>
        <div class="input-group-append">
          <%= f.button :submit, value: "Go", class: "btn btn-primary" %>
        </div>
      </div>
    </div>

    <div class="row form-group">
      <div class="input-group col-sm-10">
        <div class="input-group-prepend">
          <%= f.label :status, "Status", class: "input-group-text" %>
        </div>

        <%= f.select :status,
            status_filter_options,
            { selected: "closed"},
            {
              class: "custom-select",
              onchange: "this.form.submit()"
            }
        %>
      </div>
    </div>


    <div class="row form-group">
      <div class="input-group col-sm-10">
        <div class="input-group-prepend">
          <%= f.label :collecting_area, "Collecting Area", class: "input-group-text" %>
        </div>

        <%= f.select :collecting_area,
            collecting_area_filter_options,
            { selected: "closed"},
            {
              class: "custom-select",
              onchange: "this.form.submit()"
            }
        %>
      </div>
    </div>


  <% end %>
</div>


<% if @admin_r_and_r_items.total_count > 0 %>
  <p>
    <%= @admin_r_and_r_items.offset_value + 1 %> - <%= @admin_r_and_r_items.offset_value + @admin_r_and_r_items.count %> of <%= @admin_r_and_r_items.total_count %>
  </p>
<% end %>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th scope="col" class="w-25 p-3">Title and notes</th>
        <th scope="col" class="d-none d-sm-table-cell  w-25 p-3" >Status</th>
        <th scope="col" class="d-none d-sm-table-cell" >Deadline</th>
        <th scope="col" class="d-none d-sm-table-cell" >Collecting area</th>
        <th scope="col" class="d-none d-md-table-cell" >Bib number</th>
        <th scope="col" class="d-none d-md-table-cell" >Accession number</th>
        <th scope="col" class="d-none d-md-table-cell" >Object ID</th>
        <th scope="col" class="d-none d-md-table-cell mw-10" >Location </th>
      </tr>
    </thead>

    <tbody>
      <%@admin_r_and_r_items.each do |admin_r_and_r_item| %>
        <tr>
          <td class="w-25 p-3">
            <%= link_to admin_r_and_r_item.title, admin_r_and_r_item_path(admin_r_and_r_item)%>

            <% if admin_r_and_r_item.additional_notes.present? %>
              <small class="text-muted">
                (<%= admin_r_and_r_item.additional_notes %>)
              </small>
            <% end %>
          </td>
          <td scope="col" class="d-none d-sm-table-cell w-25 p-3">
             <%= DigitizationQueueItemStatusForm.new(admin_r_and_r_item).display %>
          </td>
          <td scope="col" class="d-none d-sm-table-cell" ><%= l(admin_r_and_r_item.deadline.to_date, format: :admin) if admin_r_and_r_item.deadline%></td>


          <td scope="col" class="d-none d-sm-table-cell" ><%= admin_r_and_r_item.collecting_area.humanize %></td>


          <td scope="col" class="d-none d-md-table-cell" ><%= link_to "#{admin_r_and_r_item.bib_number}", ScihistDigicoll::Util.opac_url(admin_r_and_r_item.bib_number), target: "_blank" if admin_r_and_r_item.bib_number %>
          </td>
          <td scope="col" class="d-none d-md-table-cell" ><%= admin_r_and_r_item.accession_number %>  </td>
          <td scope="col" class="d-none d-md-table-cell" ><%= admin_r_and_r_item.museum_object_id %>  </td>
          <td scope="col" class="d-none d-md-table-cell mw-10" >
            <small class="text-muted">
              <%= admin_r_and_r_item.location %>
            </small>
            </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= paginate @admin_r_and_r_items, theme: 'twitter-bootstrap-4' %>

app/views/admin/r_and_r_items/new.html.erb
<h1>New R &amp; R Item</h1>
<%= render 'form', admin_r_and_r_item: @admin_r_and_r_item %>

app/views/admin/r_and_r_items/show.html.erb
<div class="row mb-2">
  <div class="col">
    <h1>R&R request: <%= @admin_r_and_r_item.title %></h1>
  </div>
</div>

<div class="row">
  <div class="col">
    <div class="mb-2">
      <%= link_to 'Back to R & R list', admin_r_and_r_items_path, class: "btn btn-primary" %>
    </div>
    <div class="mb-2">
      <%= link_to 'Edit this R & R request', edit_admin_r_and_r_item_path(@admin_r_and_r_item), class: "btn btn-primary" %>
    </div>


    <div class="mb-2">
        <%# We can create a new digitization queue item based on this R&R item.  %>
        <% if @admin_r_and_r_item.digitization_queue_item.count > 0 %>
          <%# This R&R item *already* has at least one DQ item associated with it. Most likely, the user will *not* want to proceed with creating a new one. %>
          <%= link_to "Create a new Digitization Queue item",
            new_admin_digitization_queue_items_path(r_and_r_item: @admin_r_and_r_item.id,
            collecting_area: @admin_r_and_r_item.collecting_area),
            class: "btn btn-secondary",
            data: { confirm: "This R&R item has already been used to create a digitization queue item. Really continue?" }
          %>
        <% else %>
          <%# This R&R item has *no* DQ items associated with it.%>
          <%= link_to "Send to Digitization Queue", new_admin_digitization_queue_items_path(r_and_r_item: @admin_r_and_r_item.id, collecting_area: @admin_r_and_r_item.collecting_area), class: "btn btn-primary" %>
        <% end %>
    </div>

    <% if @admin_r_and_r_item.digitization_queue_item.count > 0 %>
      <dt>This R&R item already has <%= pluralize(@admin_r_and_r_item.digitization_queue_item.count, 'corresponding item') %> in the digitization queue:</dt>
      <dd>
        <ul class="list-group">
        <% @admin_r_and_r_item.digitization_queue_item.each do |dq_item| %>
          <%= link_to dq_item.title, admin_digitization_queue_items_path(dq_item),
          class: "list-group-item list-group-item-action" %>
        <% end %>
        </ul>
      </dd>
    <% end%>
  </div>
</div>


<hr/>

<div class="row">
  <div class="col-md-7 order-md-2">
    <%= render 'admin/r_and_r_items/show_first_column' %>
  </div>
  <div class="col-md-5 order-md-1 pr-4">
    <%= render 'admin/r_and_r_items/show_second_column' %>
  </div>
</div>

<hr/>

<div class="row mb-2">
  <div class="col">
    <%= link_to "Delete \"#{@admin_r_and_r_item.title}\"", admin_r_and_r_item_path(r_and_r_item: @admin_r_and_r_item.id),
      class: "btn btn-primary btn-danger",
      method: 'delete',
      data: { confirm: "Do you really want to delete \"#{@admin_r_and_r_item.title}?\"" } %>
  </div>
</div>